version: '3'
services:
  ch2:
    image: 'andrewcooke/choochoo:latest-local'
    container_name: 'choochoo'
    user: '${ID}'
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - 'choochoo-dataDEV:/data'
    depends_on:
      - 'pg'
      - 'jp'
  jp:
    image: 'andrewcooke/jupyter:latest-local'
    container_name: 'jupyter'
    user: '${ID}'
    command: 'start-notebook.sh
    --NotebookApp.notebook_dir=/data/VERSION/notebook
    --NotebookApp.token=''''
    --NotebookApp.allow_root=True'
    environment:
      - NB_UID=0
    ports:
      - '127.0.0.1:8001:8888'
    volumes:
      - 'choochoo-dataDEV:/data'
  pg:
#    image: 'postgres:11.8-alpine'
    image: 'postgis/postgis:13-3.0-alpine'
    container_name: 'postgresql'
    shm_size: '1g'
    command: '-c config_file=/etc/postgresql/postgresql.conf'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'postgresql-dataDEV:/var/lib/postgresql/data'
      - 'postgresql-logDEV:/var/log'
      - './postgres.conf:/etc/postgresql/postgresql.conf'
volumes:
  choochoo-dataDEV:
    external: true
  postgresql-dataDEV:
    external: true
  postgresql-logDEV:
    external: true
